spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/demo-order?characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
  jpa:
    generate-ddl: true
  flyway:
    enabled: true
server:
  port: 9090
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7900/eureka/
    registry-fetch-interval-seconds: 5
seata:
  registry:
    type: eureka
    eureka:
      service-url: ${eureka.client.service-url.defaultZone}
  service:
    vgroup-mapping: SEATA
  config:
    file:
      name: file.conf