spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/tx-manager?characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
  jpa:
    generate-ddl: true
server:
  port: 9090
tx-lcn:
  client:
    manager-address: 127.0.0.1:8070,127.0.0.1:8071
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7900/eureka/
