spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/demo-order?characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
  jpa:
    generate-ddl: true
  flyway:
    enabled: true
server:
  port: 9090