spring:
  application:
    name: tx-manager
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/tx-manager?characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
    # 很烦啊，引入tm之后都要重新设置
    hikari:
      username: root
      password:
  flyway:
    enabled: true
    # 很烦啊，引入tm之后都要重新设置
    url: jdbc:mysql://127.0.0.1:3306/tx-manager?characterEncoding=UTF-8
    user: root
    password:
  redis:
    host: localhost
    port: 6379
    password:
server:
  port: 7970
tx-lcn:
  logger:
    enabled: false
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    jdbc-url: jdbc:mysql://127.0.0.1:3306/tx-manager?characterEncoding=UTF-8
#    username: root
#    password:
  manager:
    host: 127.0.0.1
    port: 8070
    heart-time: 15000
    dtx-time: 30000
    current-level: 128
    admin-key: tm123
    dtx-lock-time: -1
    seq-len: 12
#  message:
#    netty:
#      attr-delay-time: 10000